apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  namespace: react
  labels:
    app: node-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
        - name: node-backend
          image: saideep12345/newsmern_backend:v1  # Replace with your image
          ports:
            - containerPort: 8080
          env:
            - name: CONNECTION_URL
              value: "mongodb://admin:password@mongodb.react.svc.cluster.local:27017/?authSource=admin"
---
apiVersion: v1
kind: Service
metadata:
  name: node-backend
  namespace: react
spec:
  selector:
    app: node-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP  # Internal service for frontend to access
